name: View Artifact

on:
  workflow_run:
    workflows: ['Build Artifact']
    types:
    - completed

jobs:
  view:
    name: View
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
    - name: Log 1
      run: ls
    - name: Log 2
      run: cat folder/file.js
    - name: Log 3
      run: cat sha/sha.txt